apiVersion: v1
kind: Service
metadata:
  name: db_container
  namespace: mysql-namespace-assign2
spec:
  selector:
    app: mysql  
  ports:
  - protocol: TCP
    port: 3306  
    targetPort: 3306
  type: ClusterIP 
