apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset-assign2
  namespace: mysql-namespace-assign2
  labels:
    app: mysql
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 105655153485.dkr.ecr.us-east-1.amazonaws.com/image-mysql-repo:updated
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: ecr-registry-secret-mysql
