apiVersion: v1
kind: Pod
metadata:
  name: webapp-assign2
  namespace: webapp-namespace-assign2
  labels:
    app: employees  
spec:
  containers:
  - name: webapp
    image: 105655153485.dkr.ecr.us-east-1.amazonaws.com/image-app-repo:latest
    env:
    - name: DBHOST
      value: "db_container.webapp-namespace-assign2.svc.cluster.local"  
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "password"
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: ecr-registry-secret  
 
