apiVersion: v1
kind: Service
metadata:
  name: webapp-service-assign2
  namespace: webapp-namespace-assign2
spec:
  selector:
    app: employees  
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80
    nodePort: 30000  
  type: NodePort
